

#ifdef __cplusplus
extern "C" {
#endif

/* new feature */
#define NDN_HELPER_BOOTSTRAP_START  (0x0400)

#define NDN_HELPER_DISCOVERY_START    (0x0401)

#define NDN_HELPER_ACCESS_CONSUMER  (0x0408)

#define NDN_HELPER_ACCESS_PRODUCER  (0x040A)

#define NDN_HELPER_DISCOVERY_QUERY    (0x0405)

#define NDN_HELPER_BOOTSTRAP_INFO    (0x0402)

#define NDN_HELPER_DISCOVERY_REGISTER_PREFIX  (0x0406)

#define NDN_HELPER_DISCOVERY_INIT  (0x0409)

#define NDN_HELPER_ACCESS_INIT  (0x040B)

#define NDN_HELPER_ACCESS_TERMINATE  (0x040C)

#ifdef __cplusplus
}
#endif

