
#ifndef NRF_SDK_BLE_NDN_LITE_BLE_UNICAST_TRANSPORT_DEFS_H
#define NRF_SDK_BLE_NDN_LITE_BLE_UNICAST_TRANSPORT_DEFS_H

/**< Maximum number of observers for the NRF SDK BLE stack. */
#define NRF_SDK_BLE_NDN_LITE_BLE_UNICAST_TRANSPORT_MAX_OBSERVERS 5

#endif // NRF_SDK_BLE_NDN_LITE_BLE_UNICAST_TRANSPORT_DEFS_H