
/*
 * Copyright (C) 2019 Edward Lu
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

#include "trust-schema-tests-def.h"

#include "../../ndn-lite/ndn-enums.h"

char *trust_schema_test_names[TRUST_SCHEMA_NUM_TESTS] = {
  "test_trust_schema_pattern_left_wildcards_match",
  "test_trust_schema_pattern_left_wildcards_mismatch",
  "test_trust_schema_pattern_right_wildcards_match",
  "test_trust_schema_pattern_right_wildcards_mismatch",
  "test_trust_schema_pattern_surrounded_wildcards_match",
  "test_trust_schema_pattern_surrounded_wildcards_mismatch",
  "test_trust_schema_pattern_no_wildcards_match",
  "test_trust_schema_pattern_no_wildcards_mismatch",
  "test_trust_schema_pattern_only_wildcards_match",
  "test_trust_schema_pattern_wildcard_specializer_match",
  "test_trust_schema_pattern_wildcard_specializer_mismatch",
  "test_trust_schema_pattern_invalid_format_multiple_consecutive_wildcard_sequences",
  "test_trust_schema_pattern_single_subpattern_match",
  "test_trust_schema_pattern_single_subpattern_mismatch",
  "test_trust_schema_pattern_multiple_subpatterns_match",
  "test_trust_schema_pattern_multiple_subpatterns_mismatch",
  "test_trust_schema_pattern_empty_subpattern_match",
  "test_trust_schema_pattern_empty_subpattern_mismatch",
  "test_trust_schema_pattern_real_length_exceeds_name_length",
  "test_trust_schema_name_length_exceeds_pattern_real_length",
  /* "test_trust_schema_name_rule_ref_match", */
};

bool trust_schema_test_results[TRUST_SCHEMA_NUM_TESTS];

trust_schema_test_t trust_schema_tests[TRUST_SCHEMA_NUM_TESTS] = {
    {
      trust_schema_test_names,
      0,
      test_rule_0_data_pattern_string,
      sizeof(test_rule_0_data_pattern_string),
      test_rule_0_key_pattern_string,
      sizeof(test_rule_0_key_pattern_string),
      test_data_name_0_string,
      sizeof(test_data_name_0_string),
      test_key_name_0_string,
      sizeof(test_key_name_0_string),
      expected_rule_compilation_return_0,
      expected_match_0,
      &trust_schema_test_results[0]
    },
    {
      trust_schema_test_names,
      1,
      test_rule_1_data_pattern_string,
      sizeof(test_rule_1_data_pattern_string),
      test_rule_1_key_pattern_string,
      sizeof(test_rule_1_key_pattern_string),
      test_data_name_1_string,
      sizeof(test_data_name_1_string),
      test_key_name_1_string,
      sizeof(test_key_name_1_string),
      expected_rule_compilation_return_1,
      expected_match_1,
      &trust_schema_test_results[1]
    },
    {
      trust_schema_test_names,
      2,
      test_rule_2_data_pattern_string,
      sizeof(test_rule_2_data_pattern_string),
      test_rule_2_key_pattern_string,
      sizeof(test_rule_2_key_pattern_string),
      test_data_name_2_string,
      sizeof(test_data_name_2_string),
      test_key_name_2_string,
      sizeof(test_key_name_2_string),
      expected_rule_compilation_return_2,
      expected_match_2,
      &trust_schema_test_results[2]
    },
    {
      trust_schema_test_names,
      3,
      test_rule_3_data_pattern_string,
      sizeof(test_rule_3_data_pattern_string),
      test_rule_3_key_pattern_string,
      sizeof(test_rule_3_key_pattern_string),
      test_data_name_3_string,
      sizeof(test_data_name_3_string),
      test_key_name_3_string,
      sizeof(test_key_name_3_string),
      expected_rule_compilation_return_3,
      expected_match_3,
      &trust_schema_test_results[3]
    },
    {
      trust_schema_test_names,
      4,
      test_rule_4_data_pattern_string,
      sizeof(test_rule_4_data_pattern_string),
      test_rule_4_key_pattern_string,
      sizeof(test_rule_4_key_pattern_string),
      test_data_name_4_string,
      sizeof(test_data_name_4_string),
      test_key_name_4_string,
      sizeof(test_key_name_4_string),
      expected_rule_compilation_return_4,
      expected_match_4,
      &trust_schema_test_results[4]
    },
    {
      trust_schema_test_names,
      5,
      test_rule_5_data_pattern_string,
      sizeof(test_rule_5_data_pattern_string),
      test_rule_5_key_pattern_string,
      sizeof(test_rule_5_key_pattern_string),
      test_data_name_5_string,
      sizeof(test_data_name_5_string),
      test_key_name_5_string,
      sizeof(test_key_name_5_string),
      expected_rule_compilation_return_5,
      expected_match_5,
      &trust_schema_test_results[5]
    },
    {
      trust_schema_test_names,
      6,
      test_rule_6_data_pattern_string,
      sizeof(test_rule_6_data_pattern_string),
      test_rule_6_key_pattern_string,
      sizeof(test_rule_6_key_pattern_string),
      test_data_name_6_string,
      sizeof(test_data_name_6_string),
      test_key_name_6_string,
      sizeof(test_key_name_6_string),
      expected_rule_compilation_return_6,
      expected_match_6,
      &trust_schema_test_results[6]
    },
    {
      trust_schema_test_names,
      7,
      test_rule_7_data_pattern_string,
      sizeof(test_rule_7_data_pattern_string),
      test_rule_7_key_pattern_string,
      sizeof(test_rule_7_key_pattern_string),
      test_data_name_7_string,
      sizeof(test_data_name_7_string),
      test_key_name_7_string,
      sizeof(test_key_name_7_string),
      expected_rule_compilation_return_7,
      expected_match_7,
      &trust_schema_test_results[7]
    },
    {
      trust_schema_test_names,
      8,
      test_rule_8_data_pattern_string,
      sizeof(test_rule_8_data_pattern_string),
      test_rule_8_key_pattern_string,
      sizeof(test_rule_8_key_pattern_string),
      test_data_name_8_string,
      sizeof(test_data_name_8_string),
      test_key_name_8_string,
      sizeof(test_key_name_8_string),
      expected_rule_compilation_return_8,
      expected_match_8,
      &trust_schema_test_results[8]
    },
    {
      trust_schema_test_names,
      9,
      test_rule_9_data_pattern_string,
      sizeof(test_rule_9_data_pattern_string),
      test_rule_9_key_pattern_string,
      sizeof(test_rule_9_key_pattern_string),
      test_data_name_9_string,
      sizeof(test_data_name_9_string),
      test_key_name_9_string,
      sizeof(test_key_name_9_string),
      expected_rule_compilation_return_9,
      expected_match_9,
      &trust_schema_test_results[9]
    },
    {
      trust_schema_test_names,
      10,
      test_rule_10_data_pattern_string,
      sizeof(test_rule_10_data_pattern_string),
      test_rule_10_key_pattern_string,
      sizeof(test_rule_10_key_pattern_string),
      test_data_name_10_string,
      sizeof(test_data_name_10_string),
      test_key_name_10_string,
      sizeof(test_key_name_10_string),
      expected_rule_compilation_return_10,
      expected_match_10,
      &trust_schema_test_results[10]
    },
    {
      trust_schema_test_names,
      11,
      test_rule_11_data_pattern_string,
      sizeof(test_rule_11_data_pattern_string),
      test_rule_11_key_pattern_string,
      sizeof(test_rule_11_key_pattern_string),
      test_data_name_11_string,
      sizeof(test_data_name_11_string),
      test_key_name_11_string,
      sizeof(test_key_name_11_string),
      expected_rule_compilation_return_11,
      expected_match_11,
      &trust_schema_test_results[11]
    },
    {
      trust_schema_test_names,
      12,
      test_rule_12_data_pattern_string,
      sizeof(test_rule_12_data_pattern_string),
      test_rule_12_key_pattern_string,
      sizeof(test_rule_12_key_pattern_string),
      test_data_name_12_string,
      sizeof(test_data_name_12_string),
      test_key_name_12_string,
      sizeof(test_key_name_12_string),
      expected_rule_compilation_return_12,
      expected_match_12,
      &trust_schema_test_results[12]
    },
    {
      trust_schema_test_names,
      13,
      test_rule_13_data_pattern_string,
      sizeof(test_rule_13_data_pattern_string),
      test_rule_13_key_pattern_string,
      sizeof(test_rule_13_key_pattern_string),
      test_data_name_13_string,
      sizeof(test_data_name_13_string),
      test_key_name_13_string,
      sizeof(test_key_name_13_string),
      expected_rule_compilation_return_13,
      expected_match_13,
      &trust_schema_test_results[13]
    },
    {
      trust_schema_test_names,
      14,
      test_rule_14_data_pattern_string,
      sizeof(test_rule_14_data_pattern_string),
      test_rule_14_key_pattern_string,
      sizeof(test_rule_14_key_pattern_string),
      test_data_name_14_string,
      sizeof(test_data_name_14_string),
      test_key_name_14_string,
      sizeof(test_key_name_14_string),
      expected_rule_compilation_return_14,
      expected_match_14,
      &trust_schema_test_results[14]
    },
    {
      trust_schema_test_names,
      15,
      test_rule_15_data_pattern_string,
      sizeof(test_rule_15_data_pattern_string),
      test_rule_15_key_pattern_string,
      sizeof(test_rule_15_key_pattern_string),
      test_data_name_15_string,
      sizeof(test_data_name_15_string),
      test_key_name_15_string,
      sizeof(test_key_name_15_string),
      expected_rule_compilation_return_15,
      expected_match_15,
      &trust_schema_test_results[15]
    },
    {
      trust_schema_test_names,
      16,
      test_rule_16_data_pattern_string,
      sizeof(test_rule_16_data_pattern_string),
      test_rule_16_key_pattern_string,
      sizeof(test_rule_16_key_pattern_string),
      test_data_name_16_string,
      sizeof(test_data_name_16_string),
      test_key_name_16_string,
      sizeof(test_key_name_16_string),
      expected_rule_compilation_return_16,
      expected_match_16,
      &trust_schema_test_results[16]
    },
    {
      trust_schema_test_names,
      17,
      test_rule_17_data_pattern_string,
      sizeof(test_rule_17_data_pattern_string),
      test_rule_17_key_pattern_string,
      sizeof(test_rule_17_key_pattern_string),
      test_data_name_17_string,
      sizeof(test_data_name_17_string),
      test_key_name_17_string,
      sizeof(test_key_name_17_string),
      expected_rule_compilation_return_17,
      expected_match_17,
      &trust_schema_test_results[17]
    },
    {
      trust_schema_test_names,
      18,
      test_rule_18_data_pattern_string,
      sizeof(test_rule_18_data_pattern_string),
      test_rule_18_key_pattern_string,
      sizeof(test_rule_18_key_pattern_string),
      test_data_name_18_string,
      sizeof(test_data_name_18_string),
      test_key_name_18_string,
      sizeof(test_key_name_18_string),
      expected_rule_compilation_return_18,
      expected_match_18,
      &trust_schema_test_results[18]
    },
    {
      trust_schema_test_names,
      19,
      test_rule_19_data_pattern_string,
      sizeof(test_rule_19_data_pattern_string),
      test_rule_19_key_pattern_string,
      sizeof(test_rule_19_key_pattern_string),
      test_data_name_19_string,
      sizeof(test_data_name_19_string),
      test_key_name_19_string,
      sizeof(test_key_name_19_string),
      expected_rule_compilation_return_19,
      expected_match_19,
      &trust_schema_test_results[19]
    },
    /* { */
    /*   trust_schema_test_names, */
    /*   20, */
    /*   test_rule_20_data_pattern_string, */
    /*   sizeof(test_rule_20_data_pattern_string), */
    /*   test_rule_20_key_pattern_string, */
    /*   sizeof(test_rule_20_key_pattern_string), */
    /*   test_data_name_20_string, */
    /*   sizeof(test_data_name_20_string), */
    /*   test_key_name_20_string, */
    /*   sizeof(test_key_name_20_string), */
    /*   expected_rule_compilation_return_20, */
    /*   expected_match_20, */
    /*   &trust_schema_test_results[20] */
    /* }, */
};
